 DATA &outsmp;
  SET &data;
  BY &id;
  RETAIN smp_flag;
  IF smp_count < &n THEN DO;
   IF FIRST.&id THEN DO;
     id_count + 1;
     IF uniform(&seed)*(&n0 - id_count) < (&n - smp_count) THEN DO;
           smp_flag=1;
          OUTPUT;
     END;
    END;
   ELSE IF smp_flag=1 THEN DO;
        OUTPUT;
        IF LAST.&id THEN DO;
             smp_flag=0;
             smp_count + 1;
        END;
   END;
  END;
  DROP smp_flag smp_count;
 RUN;
%MEND;
