PROC SURVEYSELECT DATA=MYDATA.BANKFULL RATE=0.3 OUTALL OUT=class
SEED=42; RUN;
PROC FREQ DATA=class; TABLES selected; RUN;
DATA MYDATA.BANK_TRAIN MYDATA.BANK_TEST;
  SET class;
  IF selected = 0 THEN OUTPUT MYDATA.BANK_TRAIN; ELSE OUTPUT
MYDATA.BANK_TEST;
  DROP selected;
RUN;
