DATA METRICS;
  SET MYDATA.MASTER;
  ERROR_RATE = (FP+FN)/(P+N);
  ACCURACY = (TP+TN)/(P+N);
  SENSITIVITY = TP/P;
  SPECIFICITY = TN/N;
  PRECISION = TP/(TP+FP);
  FALSE_POSITIVE_RATE = 1-SPECIFICITY;
RUN;
