proc iml;
use antihyp1;
read all var {raw_p} into p;
h=j(7,3,0);
decision_matrix=j(7,3,0);
adjusted_p=j(1,3,0);
do i=1 to 3;
do j=0 to 6;
k=floor(j/2**(3-i));
if k/2=floor(k/2) then h[j+1,i]=1;
end;
end;
do i=1 to 7;
decision_matrix[i,]=h[i,]*sum(h[i,])*min(p[loc(h[i,])]);
end;
do i=1 to 3;
adjusted_p[i]=max(decision_matrix[,i]);
end;
title={"L vs P", "M vs P", "H vs P"};
print decision_matrix[colname=title];
print adjusted_p[colname=title];
quit;
