proc iml;
* Two-sided Type I error probability;
alpha=0.05;
* Pocock plan;
Rho=0.5;
* Number of analyses;
m=5;
* Two-sided boundary on the cumulative sum scale;
SBoundary=-(1:m)##Rho//(1:m)##Rho;
call seqscale(prob,CritValue,SBoundary,1-alpha) eps=1e-8;
* Two-sided boundary on the test statistic scale;
ZBoundary=CritValue*(1:m)##(Rho-0.5);
print ZBoundary[format=7.4];
* Adjusted significance level;
AdjAlpha=2*(1-probnorm(CritValue));
print AdjAlpha[format=7.4];
* Stopping probabilities under the null hypothesis;
SBoundary=-CritValue*(1:m)##Rho//CritValue*(1:m)##Rho;
call seq(prob0,SBoundary) eps=1e-8;
StopProb=prob0[3,]-prob0[2,]+prob0[1,];
print StopProb[format=7.4];
run;
quit;
