proc iml;
* Two-sided Type I error probability;
alpha=0.05;
* Type II error probability;
beta=0.1;
* Pocock plan;
Rho=0.5;
* Number of analyses;
m=5;
start DriftSearch(d) global(m,rho,critvalue,beta);
lower=-critvalue*(1:m)##rho;
upper=critvalue*(1:m)##rho;
adjustment=d*(1:m);
boundary=(lower-adjustment)//(upper-adjustment);
call seq(p,boundary) eps=1e-8;
diff=abs(beta-(p[2,]-p[1,])[m]);
return(diff);
finish;
* Two-sided boundary on the cumulative sum scale;
SBoundary=-(1:m)##rho//(1:m)##rho;
call seqscale(prob,CritValue,SBoundary,1-alpha) eps=1e-8;
* Starting value for the drift parameter search;
start=(probit(1-beta)+probit(1-alpha))/sqrt(m);
* Convergence parameters;
tc=repeat(.,1,12);
tc[1]=100;
tc[3]=1e-5;
call nlpdd(rc,drift,"DriftSearch",start) tc=tc;
* Drift parameter;
print drift[format=6.2];
run;
quit;
