%macro LocalQSmooth(dataset,gamma,initial,outdata);
data quantile;
data _null_;
set &initial nobs=m;
call symput("n",m);
run;
%do i=1 %to &n;
data _null_;
set &initial;
if _n_=&i then do;
call symput("x",x);
call symput("inita",poly);
call symput("initb",firstder);
call symput("h",h);
end;
run;
proc nlin data=&dataset nohalve noitprint maxiter=300 converge=0.001;
parms a=&inita b=&initb;
model y=a+b*(x-&x);
der.a=1; der.b=x-&x; resid=y-model.y;
if resid>0 then w1=&gamma/resid;
if resid<0 then w1=(&gamma-1)/resid;
if resid=0 then w1=0;
w2=pdf("normal",(x-&x)/&h)/&h; _weight_=w1*w2;
