proc iml;
start ParSearch(c) global(m,lastlook,stfract,inc);
drift=(c[1]*lastlook##&rhoeff+c[2]*lastlook##&rhofut)/lastlook;
upper=c[1]*stfract##&rhoeff;
lower=drift*stfract-c[2]*stfract##&rhofut;
lower[m]=lower[m]-1e-5;
boundary=lower//upper;
call seq(p,boundary) eps=1e-8 tscale=inc;
crossh0=sum(p[3,]-p[2,])-&alpha;
adjustment=drift*stfract;
boundary=(lower-adjustment)//(upper-adjustment);
call seq(p,boundary) eps=1e-8 tscale=inc;
crossh1=sum(p[3,]-p[2,])-&power;
diff=abs(crossh0)+abs(crossh1);
return(diff);
finish;
use &fraction;
read all var _all_ into fraction;
m=nrow(fraction);
fract=t(fraction);
stfract=fract/fract[1];
inc=j(1,m-1,0);
do i=1 to m-1;
inc[i]=(fract[i+1]-fract[i])/fract[1];
end;
lastlook=stfract[m];
nfixed=2*((probit(&power)+probit(1-&alpha))/&effsize)**2;
start={1 1};
tc=repeat(.,1,12);
tc[1]=100;
tc[3]=1e-5;
call nlpdd(rc,c,"ParSearch",start) tc=tc;
drift=(c[1]*lastlook##&rhoeff+c[2]*lastlook##&rhofut)/lastlook;
upper=c[1]*stfract##&rhoeff;
lower=drift*stfract-c[2]*stfract##&rhofut;
lower[m]=lower[m]-1e-5;
boundary=lower//upper;
call seq(prob0,boundary) eps=1e-8 tscale=inc;
adjustment=drift*stfract;
