proc iml;
start DriftSearch(d) global(m,critvalue,stfract,inc,infinity);
upper=critvalue*stfract##&rho;
adjustment=d*stfract;
boundary=infinity//(upper-adjustment);
call seq(p,boundary) eps=1e-8 tscale=inc;
diff=abs(1-&power-(p[2,]-p[1,])[m]);
return(diff);
finish;
start BoundSearch(new) global(stage,alpha,adjbound,sinf,infinc);
alphainc=alpha[stage]-alpha[stage-1];
tempb=t(adjbound[1:stage]#sqrt(sinf[1:stage]));
tempb[stage]=new*sqrt(sinf[stage]);
tempinf=repeat(.m,1,stage);
tempinc=t(infinc[1:stage-1]);
boundary=tempinf//tempb;
call seq(p,boundary) eps=1e-8 tscale=tempinc;
diff=abs(p[3,stage]-p[2,stage]-alphainc);
return(diff);
finish;
start AdjQuant(est) global(quantile,sall,observed,tempinc,infinity);
adjustment=est*sall;
upper=observed#(sall##0.5);
boundary=infinity//(upper-adjustment);
call seq(prob,boundary) eps=1e-8 tscale=tempinc;
sss=sum(prob[3,]-prob[2,]);
diff=abs(quantile-sss);
return(diff);
finish;
use &fraction;
read all var _all_ into fraction;
m=nrow(fraction);
fract=t(fraction);
stfract=fract/fract[1];
inc=j(1,m-1,0);
do i=1 to m-1;
inc[i]=(fract[i+1]-fract[i])/fract[1];
end;
infinity=repeat(.m,1,m);
upper=stfract##&rho;
boundary=infinity//upper;
call seqscale(prob,critvalue,boundary,1-&alpha) eps=1e-8 tscale=inc;
upper=critvalue*stfract##&rho;
boundary=infinity//upper;
call seq(prob1,boundary) eps=1e-8 tscale=inc;
spend1=cusum(prob1[3,]-prob1[2,]+prob1[1,]);
beta=1-&power;
nfixed=2*((probit(&power)+probit(1-&alpha))/&effsize)**2;
Appendix
start=&effsize*sqrt(nfixed*fract[1]/2);
tc=repeat(.,1,12);
tc[1]=100;
tc[3]=1e-5;
call nlpdd(rc,drift,"DriftSearch",start) tc=tc;
max=2*(drift/&effsize)*(drift/&effsize)/fract[1];
use &data;
read all var {n stat} into mon;
n=nrow(mon);
ss=mon[,1];
infofrac=ss/max;
statistic=mon[,2];
pvalue=1-probnorm(mon[,2]);
sinf=infofrac/infofrac[1];
if n>1 then do;
infinc=j(1,n-1,0);
do i=1 to n-1;
infinc[i]=sinf[i+1]-sinf[i];
end;
end;
else infinc=j(1,1,1);
alpha=j(n,1,0);
level=j(n,1,0);
adjbound=j(n,1,0);
tc=repeat(.,1,12);
tc[1]=200;
tc[3]=1e-6;
* Design-based error spending function;
if &spfunction=1 then
do;
t=0 || fract;
s=0 || spend1;
do stage=1 to n;
x=infofrac[stage];
do i=1 to m;
if t[i]<=x & x<t[i+1] then
alpha[stage]=(s[i+1]*(x-t[i])+s[i]*(t[i+1]-x))/
(t[i+1]-t[i]);
end;
if x>=1 then alpha[stage]=&alpha;
end;
end;
* Ten-look error spending function;
if &spfunction=2 then
do;
k=10;
infinity=repeat(.m,1,k);
upper=(1:k)##&rho;
boundary=infinity//upper;
call seqscale(prob,critvalue,boundary,1-&alpha) eps=1e-8;
upper=critvalue*(1:k)##&rho;
boundary=infinity//upper;
call seq(prob0,boundary) eps=1e-8;
spend=t(cusum(prob0[3,]-prob0[2,]+prob0[1,]));
do stage=1 to n;
x=infofrac[stage];
