proc iml;
start ParSearch(c) global(lastlook,scf,scale);
drift=(c[1]*lastlook##&rhoeff+c[2]*lastlook##&rhofut)/lastlook;
upper=c[1]*scf##&rhoeff;
lower=drift*scf-c[2]*scf##&rhofut;
length=ncol(lower);
lower[length]=lower[length]-1e-5;
boundary=lower//upper;
call seq(p,boundary) eps=1e-8 tscale=scale;
crossh0=sum(p[3,]-p[2,])-&alpha;
adjustment=drift*scf;
boundary=(lower-adjustment)//(upper-adjustment);
call seq(p,boundary) eps=1e-8 tscale=scale;
crossh1=sum(p[3,]-p[2,])-&power;
diff=abs(crossh0)+abs(crossh1);
return(diff);
finish;
start BoundSearch(guess) global(stage,alpha,beta,adjlower,adjupper,
ss,sinf,infinc);
if guess[1]>guess[2] then do;
alphainc=alpha[stage]-alpha[stage-1];
betainc=beta[stage]-beta[stage-1];
tempupp=t(adjupper[1:stage]#sqrt(sinf[1:stage]));
templow=t(adjlower[1:stage]#sqrt(sinf[1:stage]));
tempinc=t(infinc[1:stage-1]);
tempupp[stage]=guess[1]*sqrt(sinf[stage]);
templow[stage]=guess[2]*sqrt(sinf[stage]);
boundary=templow//tempupp;
call seq(p,boundary) eps=1e-8 tscale=tempinc;
crossh0=p[3,stage]-p[2,stage]-alphainc;
adjustment=&effsize*t(sqrt(ss[1:stage]#sinf[1:stage]/2));
boundary=(templow-adjustment)//(tempupp-adjustment);
call seq(p,boundary) eps=1e-8 tscale=tempinc;
crossh1=p[1,stage]-betainc;
diff=abs(crossh0)+abs(crossh1);
return(diff);
end;
if guess[1]<=guess[2] then do;
diff=1;
return(diff);
end;
finish;
start AdjQuant(est) global(quantile,sall,observed,tempinc,infinity);
adjustment=est*sall;
upper=observed#(sall##0.5);
boundary=infinity//(upper-adjustment);
call seq(prob,boundary) eps=1e-8 tscale=tempinc;
sss=sum(prob[3,]-prob[2,]);
diff=abs(quantile-sss);
return(diff);
finish;
use &fraction;
read all var _all_ into fraction;
m=nrow(fraction);
fract=t(fraction);
stfract=fract/fract[1];
inc=j(1,m-1,0);
