data prob;
x = 2;
* x value;
n1 =  cdf('normal',x,1,1);
* prob[N(1,1)<=x];
n2 =  cdf('normal',x,2,1);
* prob[N(2,1)<=x];
n3 =  1-cdf('normal',x,3,1);
* prob[N(3,1)>x];
t1 =  cdf('T',x,4);
* prob[T(4)<=x];
t2 =  1-cdf('T',x,10);
* prob[T(10)>x];
c1 =  cdf('chisquare',x,4);
* prob[chisq(4)<=x];
c2 =  1-cdf('chisquare',x,10);
* prob[chisq(10)>x];
f1 =  cdf('F',x,4,30);
* prob[F(4,30)<=x];
f2 =  1-cdf('F',x,10,30);
* prob[F(10,30)>x];
run;
proc print data=prob;
var n1 n2 n3;
title 'normal probability computations';
run;
proc print data=prob;
var t1 t2;
title 't-distribution probability computations';
run;
proc print data=prob;
var c1 c2;
title 'chi-square distribution probability computations';
run;
proc print data=prob;
var f1 f2;
title 'F-distribution probability computations';
run;
