data mle;
* create data set;
phat = 1/4;
* starting value;
do n = 1 to 7;
* do-loop 7 iterations;
loglike = 2*log(phat)+log(1-phat);
* log-likelihood function;
g = 2/phat - 1/(1-phat);
* gradient;
h = -2/phat**2 - 1/(1-phat)**2;
* hessian;
phat = phat - (h**-1)*g;
* Newton Raphson step;
output;
* write to sas data set;
end;
* end do-loop;
run;
proc print data=mle;
var n phat loglike g h;
title 'MLE for coin flip example';
run;
