%let dsn = clinics;
%let obs = 10;
%macro look;
  title "data set &dsn";
  proc contents data=&dsn;
    run;
  title2 "first &obs observations";
  proc print data=&dsn (obs=&obs);
    run;
%mend look;
