data work.IBM1998WithVolumeInMillions;
retain MinClose MinVolume 999999999999 MaxClose MaxVolume 0;
set sashelp.Stocks end=LastOne;
where year(Date) EQ 1998 and Stock EQ 'IBM';
Volume = Volume / 1000000;
output;
MinVolume = min(MinVolume,Volume);
MaxVolume = max(MaxVolume,Volume);
MinClose = min(MinClose,Close);
MaxClose = max(MaxClose,Close);
if LastOne;
call symput('MaxCloseDisplay',trim(left(put(MaxClose,6.2))));
call symput('MaxClose',MaxClose);
call symput('MaxVolumeDisplay',trim(left(put(MaxVolume,6.2))));
call symput('MaxVolume',MaxVolume);
call symput('MinCloseDisplay',trim(left(put(MinClose,6.2))));
call symput('MinClose',MinClose);
call symput('MinVolumeDisplay',trim(left(put(MinVolume,6.2))));
call symput('MinVolume',MinVolume);
run;
