%macro smooth (data=_last_, time=, width=, survival=survival);
data _inset_;
set &data end=final;
retain _grp_ _censor_ 0;
t=&time;
survival=&survival;
if t=0 and survival=l then _grp_=_grp_+l;
keep _grp_ t survival;
if final and _grp_ > 1 then call symput('nset','yes');
else if final then call symput('nset','no1);
if _censor_=l then delete;
if survival in (0,1) then delete;
run;
proc iml;
use _inset_;
read all var {t _grp_};
%if &width ne %then %let w2=&width;
%else %let w2=(max(t)-min(t))/5;
w=&w2;
Macro Programs
z=char(w,8,2);
call symput('width',z);
numset=max(_grp_);
create _plt_ var{ lambda s group};
setin _inset_ ;
do m=l to numset;
read all var {t survival _grp_} where (_grp_=m);
n=nrow(survival);
lo=t[l] + w;
hi=t[n] - w;
npt=50;
inc=(hi-lo)/npt;
s=lo+(1:npt)"*inc;
group=j(npt,l,m);
slag=l//survival[1:n-l];
h=l-survival/slag;
x=(j(npt,l,l)*t* - s*j(l,n,l))/w;
k=.75*(l-x#x)#(abs(x)<=l);
lambda=k*h/w;
append;
end;
quit;
%if &nset=yes %then %let c==group;
%else %let c=;
proc gplot data=_plt_;
plot lambda*s &c / vaxis=axisl vzero haxis=axis2;
axisl label=(angle=90 f=titalic 'Hazard Function1 ) minor=none ;
axis2 label=(f=titalic "Time
(bandwidth=&width)") minor=none;
symboll i=join color=black line=l;
symbol2 i=join color=red line=2;
symbols i=join color=green line=3;
symbol4 i=join color=blue line=4;
run;
quit;
%mend smooth;
