ods listing close;
* Compute mean squared error;
proc glm data=hypertension;
class dose;
model change=dose;
ods output FitStatistics=mse(keep=rootmse);
* Compute n and treatment mean in placebo group;
proc means data=hypertension;
where dose=0;
var change;
output out=placebo(keep=n1 mean1) n=n1 mean=mean1;
* Compute n and treatment mean in dose groups;
proc means data=hypertension;
where dose>0;
class dose;
var change;
output out=dose(where=(dose^=.)) n=n2 mean=mean2;
* Prespecified testing sequence;
data dose;
set dose;
if _n_=1 then set mse;
if _n_=1 then set placebo;
if dose=10 then order=3;
if dose=20 then order=2;
if dose=40 then order=1;
* Order doses;
proc sort data=dose;
by order;
