proc print data=mstat3 noobs label;
var icc lower upper;
run;
* Concordance correlation coefficient;
data transpose;
set inventory;
by patient;
retain base;
if first.patient=1 then base=sip;
if last.patient=1 then post=sip;
diff=base-post;
if last.patient=1;
proc means data=transpose noprint;
var base post diff;
output out=cccout mean=mn_base mn_post mn_diff var=var_base var_post var_diff;
data cccout;
set cccout;
format ccc 5.3;
ccc=(var_base+var_post-var_diff)/(var_base+var_post+mn_diff**2);
label ccc='CCC';
proc print data=cccout noobs label;
var ccc;
run;
* Bradley-Blackwood test;
data bb;
set transpose;
avg=(base+post)/2; difsq=diff**2; sdifsq+difsq;
dum=1;
run;
proc sort data=bb;
by dum;
data bbs;
set bb;
by dum;
if last.dum;
keep sdifsq;
proc mixed data=bb method=type3;
model diff=avg;
ods output type3=bb1;
data bb1;
set bb1;
if source='Residual';
mse=ms; sse=ss; dfe=df;
keep mse sse dfe;
data test;
merge bb1 bbs;
format f p 5.3;
f=0.5*(sdifsq-sse)/mse;
p=1-probf(f,2,dfe+2);
label f='F statistic'
p='P-value';
proc print data=test noobs label;
var f p;
run;
