proc lp data=projects activeout=results;
proc transpose data=results out=results;
proc sort data=results;
by _name_;
proc transpose data=projects out=projects;
id _id_;
proc sort data=projects;
by _name_;
data together (rename=(_name_=Projects));
merge projects results;
by _name_;
activity=col1;
index=reward/cost;
if substr(_name_,1,7)="project";
keep _name_ cost reward index activity;
proc sort data=together;
by descending index;
proc print data=together;
run;
