data indicator(keep=proportion);
   set postout;
   proportion=(exp(gamma1)<&delta);
run;
proc means data=indicator n mean noprint;
   var proportion;
   output out=outpower mean=pfhat;
run;
data outpower;
   set outpower;
   simid=&m;
   keep simid pfhat;
run;
%if &m=1 %then %do;
   data proportion&s;
      set outpower;
   run;
%end;
%else %do;
   data proportion&s;
      set proportion&s outpower;
   run;
%end;
data Type1Error;
   set proportion0;
   keep pfhat BP1 BP2 BP3 BP4;
   BP1=0;BP2=0;BP3=0;BP4=0;
   if pfhat>=0.90  then BP1=1;
   if pfhat>=0.95  then BP2=1;
   if pfhat>=0.975 then BP3=1;
   if pfhat>=&eta0 then BP4=1;
run;
