proc sort data = summaries;
  by parameter;
run;
proc sort data = intervals;
  by parameter;
run;
data combined (drop=alpha);
  merge summaries intervals;
    by parameter;
run;
data _plot;
  retain logite0 .;
  set combined;
  if parameter = 'e0' then do;
    logite0 = mean;
    e0 = exp(mean)/(exp(mean)+1);
    call symput("e_0", put(e0, best8.));
  end;
  else if parameter = 'ed50' then call symput("ed_50", put(mean, best8.));
  else if parameter = 'emax' then do;
    temp = (exp(mean+logite0)/(exp(mean+logite0)+1));
    call symput("maxeffect", put(temp, best8.));
  end;
  else if parameter = 'pipred0' then dose = 0;
  else if parameter = 'pipred1' then dose = 1;
  else if parameter = 'pipred3' then dose = 3;
  else if parameter = 'pipred9' then dose = 9;
  if parameter in ('pipred0', 'pipred1', 'pipred3', 'pipred9');
run;
data plot_dt;
  label pct_col = "Observed Proportion";
  label mean    = "Posterior Proportion";
  merge _plot sum_dt;
    by dose;
  dose_jit = dose + 0.1;
  pct_col = pct_col / 100;
run;
proc sgplot data = plot_dt;
  *title1 "Observed and Emax Posterior Estimates for SRI Response";
  *title2 "with 95% Highest Posterior Density Intervals";
  scatter x = dose_jit y = pct_col /
     markerattrs=(symbol=circlefilled color=red) name="scat1";
  scatter x = dose y = mean / yerrorlower = hpdlower yerrorupper = hpdupper
   markerattrs=(symbol=circlefilled color=black)
   errorbarattrs=(color=black) name = "scat2";
  series  x = dose y = mean / lineattrs=(pattern=solid color = black);
  xaxis values = (0 1 3 9 ) label = "Dose" offsetmin=0.03 offsetmax=0.03;
  yaxis values = (0 to 1 by 0.2) label = "Proportion of SRI Responders";
  refline &e_0 &maxeffect / axis = y;
  keylegend "scat1" "scat2" / title = " " noborder;
run;
