%macro MSpower(beta, p1, p2, p3, alpha);
   data result;
      delta=1-(&alpha/2);
      za=quantile('Normal', delta);
      p1=&p1; p2=&p2; p3=&p3;alpha=&alpha;
      do i= 1 to 10000;
         nsize=i;
         denum=(i**2)*( p1*(1-p1) + (i-1)*(p2 + p3 - 2*(p1**2)) );
         den=sqrt(denum);
         a=(0.5* (i**2) + za*sqrt((i**2)*(2*i + 1)/12) - 0.5 - (i**2)*p1)/den
         beta= CDF('Normal', a);
         power=1-beta;
         output;
         if beta<=&beta then i=10001;
      end;
   run;
   data result2;
      set result end =_end;
      end=_end;
      if end;
      if beta>&beta then do;
        warning=1;
        nsize2=">10000";
      end;
      else do;
        nsize2=compress(nsize);
      end;
      label nsize2='sample size';
    run;
   proc format;
      value wa 1='required sample size greater than 10000';
   run;
   proc print noobs label;
     var nsize2 p1 p2 p3 alpha beta power warning;
     format warning wa.;
   run;
%mend MSpower;
%MSpower(0.2, 0.7, 0.6, 0.4, 0.05);
