%macro power(pe, pc, alpha, N);
data result;
pe=&pe;
pc=&pc;
alpha=&alpha;
N=&N;
b=1-&alpha;
pbar=(pe+pc)/2;
za=quantile('Normal', b);
num=(pe-pc)-za*sqrt(pbar*(1-pbar)*4/N);
den=sqrt(pe*(1-pe)*2/N+pc*(1-pc)*2/N);
a=num/den;
power=CDF('Normal', a);
run;
proc print noobs;
var pe pc N alpha power;
run;
%mend power;
%power(0.5, 0.2, 0.05, 100);
