%let VARLIST=
  Age BMI_B BPIInterf_B BPIPain_B CPFQ_B FIQ_B GAD7_B ISIX_B PHQ8_B
  PhysicalSymp_B SDS_B SatisfCare DXdur;
PROC MI DATA = REFL ROUND=.001 NIMPUTE=100 SEED=123456
OUT=DAT_MI NOPRINT;
   VAR &VARLIST BPIPain_LOCF;
RUN;
PROC SORT DATA=DAT_MI;
BY _IMPUTATION_;
RUN;
PROC PSMATCH DATA = DAT_MI REGION=ALLOBS;
   CLASS COHORT Gender Race Dr_Rheum Dr_PrimCare;
   PSMODEL COHORT(TREATED='OPIOID') = &VARLIST Gender Race Dr_Rheum
Dr_PrimCare;
   OUTPUT OUT = DAT_PS PS = _PS_;
   BY _IMPUTATION_;
RUN;
