%macro fit_psNone(dat); *fit;
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat);
%mend fit_psNone;
%macro prd_psNone(dat); * prediction i.e. ps1=P(T=1);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat);
  data tprd;
    set dat;
    if T=1 then ps1=1; * ipw will be 1;
    if T=0 then ps1=0; * ipw will be 1;
  run;
%mend prd_psNone;
* PS via logistic on main effects using missing pattern approach;
%macro fit_psMELR(dat);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat);
  %local cnvrg1 cnvrg2;
  proc logistic data=&dat outmodel=tmdl1;
    where DxDur>.;
    class T &tcatlst1/param=ref;
    model T(event='1')=&tcatlst1 &tcntlst1/firth maxiter=1000;
  run;
  %let cnvrg1=&syserr;
  proc logistic data=&dat outmodel=tmdl2;
    where DxDur=.;
    class T &tcatlst2/param=ref;
    model T(event='1')=&tcatlst2 &tcntlst2/firth maxiter=1000;
  run;
  %let cnvrg2=&syserr;
  %if %eval(&cnvrg1+&cnvrg2)=0
    %then %let fit=tmdl1 tmdl2;
    %else %let fit=failure;
%mend fit_psMELR;
%macro prd_psMELR(dat);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &fit);
  proc logistic inmodel=%scan(&fit,1);
    score data=&dat(where=(DxDur>.)) out=tprd1;
  run;
  proc logistic inmodel=%scan(&fit,2);
    score data=&dat(where=(DxDur=.)) out=tprd2;
  run;
  data tprd;
    set tprd1 tprd2;
    ps1=p_1;
    by ordr;
  run;
%mend prd_psMELR;
***************************************************************;
