%macro prd_PLM(dat,dout);
  * applies the model stored in ymdl to data &dat and produces the dataset &dout with
predictions;
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &dout);
  proc plm restore=ymdl;
    score data=&dat out=&dout(keep=ordr yprd) pred=yprd;
  run;
%mend prd_PLM;
***************************************************************;
* Outcome model as simple average;
* wts is the name of the IPW weights;
%macro fit_Mean(dat,wts);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &wts);
  proc glm data=&dat;
    class T;
    model Y=T;
    store ymdl;
    weight &wts;
  run;
  quit;
%mend fit_Mean;
%macro prd_Mean(dat,dout=yprd);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &dout);
  %prd_PLM(&dat,&dout);
%mend prd_Mean;
***************************************************************;
* Outcome model as regression on main effects;
%macro fit_Regression(dat,wts);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &wts);
  proc glm data=&dat;
    class T &ocatlst;
    model Y=T &ocatlst &ocntlst;
    store ymdl;
    weight &wts;
  run;
  quit;
%mend fit_Regression;
%macro prd_Regression(dat,dout=yprd);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &dout);
  %prd_PLM(&dat,&dout);
%mend prd_Regression;
***************************************************************;
* Outcome model as overlap weighted regression on main effects;
%macro fit_RegressionOw(dat,wts);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &wts);
  %local psowvar;
  %let psowvar=psow%substr(&wts,4); * get the name of overlap weighting variable;
  proc glm data=&dat;
    class T &ocatlst;
    model Y=T &ocatlst &ocntlst;
    weight &psowvar;
    store ymdl;
  run;
  quit;
%mend fit_RegressionOw;
%macro prd_RegressionOw(dat,dout=yprd);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &dout);
  %prd_PLM(&dat,&dout);
%mend prd_RegressionOw;
***************************************************************;
* Outcome model as 1:1 greedy matching with replacement;
* The TE (for change in BPIPain) is adjusted for baseline pain (BPIPain_B);
%macro fit_MatchGr11Tt(dat,wts);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &wts);
  %local psvar nbins EstAte;
  %let psvar=ps%substr(&wts,4); * get the name of PS variable;
  * NN matching on logit(PS) with caliper=.2*StdDev(lps);
  proc psmatch data=&dat region=allobs;
    where &psvar>.;
    class T;
    psdata treatvar=T(treated='1') ps=&psvar;
    match method=replace(k=1) distance=lps caliper(mult=stddev)=.2;
    output out(obs=match)=mtchs1 matchattwgt=matchattwgt matchid=matchid;
  run;
  * NN matching gives ATT. In order to get ATE we will flip the treatment;
  proc psmatch data=&dat region=allobs;
    where &psvar>.;
    class T;
    psdata treatvar=T(treated='0') ps=&psvar;
    match method=replace(k=1) distance=lps caliper(mult=stddev)=.2;
    output out(obs=match)=mtchs0 matchattwgt=matchattwgt matchid=matchid;
  run;
  * and for ATE we will combine 2 sets;
  data mtchs;
         set mtchs1 mtchs0;
  run;
  * adjust ATE for baseline BPIPain;
  proc glm data=mtchs;
    class T/ref=first;
    model Y=T BPIPain_B/solution;
    ods output ParameterEstimates=pe;
    weight matchattwgt;
  run;
  quit;
  proc sql;
    select estimate into :EstAte from pe where substr(parameter,1,1)='T' and
        stderr~=.; * estimated adjusted ATE;
    select count(distinct binN) into :nbins from &dat; * #bins in the input
data;
  quit;
  %let fit=&EstAte;
  %if &nbins=%eval(&exeDatBinN-1) %then %do;
    * the fit is on training bins (not on all data): so for the prediction on the
      hold-out bin we will need the training data and the name of PS variable;
    %let fit=&fit#&dat#&psvar;
  %end;
%mend fit_MatchGr11Tt;
%macro prd_MatchGr11Tt(dat,dout=yprd);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &dout &fit);
  %local nbins EstAte psvar trts;
  * get number of distinct bins;;
  proc sql;
    select count(distinct binN) into :nbins from &dat;
  quit;
  %if &nbins>1 %then %do;
