       proc univariate data=dattr(where=(T=&trts));
              var psMELR_1;
              class PSS;
              output out=univ max=maxPS;
       run;
  proc iml;
    * from training data - use records with the same T as hold-out &dat;
    use dattr(where=(T=&trts));
      read all var {&psvar} into PStr;
      read all var {PSS} into strtr;
      read all var {Y} into Ytr;
    close dattr;
              use univ; read all into PssMax; close univ; *max(PS) for each training
              strata;
    * PS from hold-out;
    use &dat;
      read all var {&psvar} into PSte;
    close %scan(&dat,1);
    * for each record from hold-out bin find its training strata;
    strte=j(nrow(PSte),1,.);
              do ite=1 to nrow(PSte);
                     if PSte[ite]>max(PStr) then strte[ite]=max(strtr);
                     else do itr=nrow(PssMax) to 1 by -1;
                            if PSte[ite]<=PssMax[itr,2] then strte[ite]=PssMax[itr,1];
                     end;
              end;
    create psste var {strte};
    append;
    close psste;
  quit;
  * predict outcome for hold-out records using adj. models fitted on training data;
  data datte;
    merge &dat psste;
    rename strte=pss;
  run;
  %prd_PLM(datte,&dout);
%mend prd_StratPS5;
***************************************************************;
* Outcome model as stratification into optimal number of strata: Rubin/Imbens
  approach (see 17.3; Imbens and Rubin 2015);
