%macro fit_StratAuto(dat,wts);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &wts);
  %local psvar nbins EstAte nB B;
  %let psvar=ps%substr(&wts,4);
  * get strata limits (B);
  proc iml;
    use &dat;
      read all var {T} into W;
      read all var {&psvar} into e;
    close %scan(&dat,1);
    L=log(e/(1-e));
    B=0;
    tmax=1.96;
    Nmin1=3;
    Nmin2=10;
    * for strata [blo,bup): calculate Nc, Nt, t-stat, and median(PS);
    start calc(blo,bup) global(W,L,e);
      B=blo<=e & e<bup;
      Nc=sum((1-W)#B);
      Nt=sum((  W)#B);
      tL=.;
      if Nt>0 & Nc>0 & Nt+Nc>2 then do;
        Lc=1/Nc#sum((1-W)#B#L);
        Lt=1/Nt#sum((  W)#B#L);
        s2L=1/(Nt+Nc-2)#(sum((1-W)#B#(L-Lc)##2) +
                         sum((  W)#B#(L-Lt)##2));
        if s2L<>0 then tL=(Lt-Lc)/sqrt(s2L#(1/Nc+1/Nt));* t-statistic;
      end;
      me=median(e[loc(e#B)]);
      return(Nc||Nt||tL||me);
    finish;
    Btmp={0 1};
    ib=1;
    ie=1;
