  data strats;
    set &dat;
    array Blimits(%eval(1+&nB)) (&B);
    pss=.;
    do i=1 to &nB;
      if &psvar>=Blimits(i) then pss=i;
    end;
    drop Blimits: i;
  run;
  proc sort data=strats;
    by pss;
  run;
  * adjust ATE;
  proc glm data=strats;
    class T/ref=first;
    model Y=T BPIPain_B/solution;
    ods output ParameterEstimates=pe;
    by PSS;
    store ymdl;
  run;
  quit;
  proc sql;
    create table ests as select distinct PSS, estimate from pe where
       substr(parameter,1,1)='T' and stderr~=.;
    create table tots as select distinct PSS, count(*) as n from strats group PSS;
    create table estsn as select * from ests natural join tots;
    select sum(n*estimate)/sum(n) into :EstAte from estsn;
    select count(distinct binN) into :nbins from &dat;
  quit;
  %let fit=&EstAte;
  %if &nbins=%eval(&exeDatBinN-1) %then %do;
    %let fit=&fit#strats#&psvar;
  %end;
%mend fit_StratAuto;
%macro prd_StratAuto(dat,dout=yprd);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &dat &fit);
  %prd_StratPS5(&dat,dout=&dout);
%mend prd_StratAuto;
***************************************************************;
