%macro PSs(tmthd,dat);
  %local mnam; %let mnam=&sysmacroname; %verbose(&mnam &tmthd &dat);
  * for tmthd the fit_&tmthd macro will fit the PS model and the prd_&tmthd macro
    will predict the PS;
  * distinct bins on dat;
  %local i bins bin;
  proc sql;
    select distinct(binN) into :bins separated by ' ' from &dat;
  quit;
  * all data;
  data dall;
    set &dat;
  run;
  * fit PS model on all data;
  %let fit=;
  %fit_&tmthd(dall);
  * get PS on all data;
  %if "&fit"="failure" %then %do;
    * if problem with fit then set all PS to .;
    data tprd;
      set dall;
     &tmthd._all=.;
      ipw%substr(&tmthd,3)_all=.;
      psow%substr(&tmthd,3)_all=.;
    run;
  %end; %else %do;
    * PS model Ok so predict PS, calculate ipw, and ps overlap weights;
    %prd_&tmthd(dall);
    data tprd;
      set tprd;
      if ps1>0 then ps1=max(1e-9,ps1); * to avoid psmatch ERROR: The input propensity
score 9.663205E-11 is less than or equal to 0.;
      &tmthd._all=ps1;
      if T=1 then ipw%substr(&tmthd,3)_all=1/ps1;
      if T=0 then ipw%substr(&tmthd,3)_all=1/(1-ps1);
      if T=1 then psow%substr(&tmthd,3)_all=1-ps1;
      if T=0 then psow%substr(&tmthd,3)_all=ps1;
    run;
  %end;
  data dpss;
    merge dpss tprd(keep=ordr &tmthd._all ipw%substr(&tmthd,3)_all
        psow%substr(&tmthd,3)_all);
    by ordr;
  run;
  * now build model on training bins and predict PS on the hold-out bin;
  %do i=1 %to %sysfunc(countw(&bins));
    %let bin=%scan(&bins,&i);
    * training bins;
    data dtrn;
      set dall;
      where binN~=&bin;
    run;
    * hold-out bin;
    data dtst;
      set dall;
      where binN=&bin;
    run;
    * fit PS model on training bins;
    %let fit=;
    %fit_&tmthd(dtrn);
    * get PS on training bins;
    %if "&fit"="failure" %then %do;
      * if problem with fit then set all PS to .;
      data tprd;
        set dtrn;
        &tmthd._&bin=.;
        ipw%substr(&tmthd,3)_&bin=.;
        psow%substr(&tmthd,3)_&bin=.;
      run;
      data tprd_&bin;
        set tprd;
      run;
      data dpss_&bin;
        set dpss;
      run;
    %end; %else %do;
      %prd_&tmthd(dtrn);
      data tprd;
        set tprd;
        if ps1>0 then ps1=max(1e-9,ps1); * to avoid psmatch ERROR: The input
             propensity score 9.663205E-11 is less than or equal to 0.;
        &tmthd._&bin=ps1;
        if T=1 then ipw%substr(&tmthd,3)_&bin=1/ps1;
        if T=0 then ipw%substr(&tmthd,3)_&bin=1/(1-ps1);
        if T=1 then psow%substr(&tmthd,3)_&bin=1-ps1;
        if T=0 then psow%substr(&tmthd,3)_&bin=ps1;
      run;
    %end;
    data dpss;
      merge dpss tprd(keep=ordr &tmthd._&bin ipw%substr(&tmthd,3)_&bin
          psow%substr(&tmthd,3)_&bin);
      by ordr;
    run;
    * get PS on test bin;
    %if "&fit"="failure" %then %do;
      * if problem with fit then set all PS to .;
      data tprd;
        set dtst;
        &tmthd._&bin=.;
        psow%substr(&tmthd,3)_&bin=.;
      run;
    %end; %else %do;
      %prd_&tmthd(dtst);
      data tprd;
        set tprd;
        if ps1>0 then ps1=max(1e-9,ps1); * to avoid psmatch ERROR: The input
            propensity score 9.663205E-11 is less than or equal to 0.;
        &tmthd._&bin=ps1;
        if T=1 then psow%substr(&tmthd,3)_&bin=1-ps1;
        if T=0 then psow%substr(&tmthd,3)_&bin=ps1;
      run;
    %end;
    data dpss;
      merge dpss tprd(keep=ordr &tmthd._&bin psow%substr(&tmthd,3)_&bin);
      by ordr;
    run;
  %end;
%mend PSs;
***************************************************************;
