proc transpose data=gps out=gpsdatt prefix=ps;
  by subjid cohort;
  var ps;
run;
* based on Crump et al. (2009);
%let lambda=;
proc iml;
  use gpsdatt(keep=ps:); read all into pscores; close gpsdatt;
  start obj1(alpha) global(gx);
    uid=gx<alpha;
    return(mean(gx#uid)/mean(uid));
  finish;
  start obj(alpha) global(gx);
    uid=gx<alpha;
    return(mean(gx#uid)/mean(uid)##2);
  finish;
  gx=(1/pscores)[,+];
  mx0=median(gx);
  call nlpnms(rc,xr,'obj') x0=mx0;
  xr=2#obj1(xr);
  *one step is often sufficient, i.e. the later integration does not change
   the value of alpha. To be safe, you can iterate;
  xr=2#obj1(xr);
  call symputx('lambda',xr);
  create gx var {gx}; append; close gx;
quit;
data gpsdatt;
  merge gpsdatt gx;
  trim=gx>&lambda;
run;
title1 "trimming details";
proc freq data=gpsdatt;
  table trim*cohort;
run;
title1;
data gps;
  merge gps gpsdatt(keep=subjid trim);
  by subjid;
  if ~trim;
  drop trim;
run;
* create numerical equivalent (_leveln_) of the cohort;
proc sql;
       create table cohorts as
              select distinct cohort
              from gps;
quit;
* we will need the format to report this numerical cohort;
data cohorts;
       set cohorts;
       W=_n_;
       fmtname='cohort';
       cfmtname='$cohort';
run;
proc format cntlin=cohorts(rename=(W=start cohort=label));
run;
proc format cntlin=cohorts(drop=fmtname rename=(cohort=start W=label
     cfmtname=fmtname));
run;
* add numerical cohort;
data dgps;
       set gps;
       _leveln_=input(put(_level_,$cohort.),best.);
run;
data dpat;
       set dgps;
       where _level_=cohort;
       drop _level_;
       rename _leveln_=W;
run;
* horizontal version of ps data;
proc transpose data=dgps out=dgpst prefix=ps_orig_;
       var ps;
       id _leveln_;
       by subjid;
run;
* add level-specific PSscores to patient level data;
data dpat;
       merge dpat dgpst(keep=subjid ps_orig_:);
       by subjid;
run;
