PROC GENMOD DATA = WT;
  WHERE VISIT_ NE 5;
  CLASS VISIT_ SUBJID_ OPIyn;
  WEIGHT STABWT;
  MODEL chgf_BPI = BPIPain_B VISIT_ OPIyn VISIT_*OPIyn
                / DIST=NORMAL LINK=ID TYPE3;
  REPEATED SUBJECT = SUBJID_ / TYPE=EXCH;
  LSMEANS OPIyn VISIT_*OPIyn/ PDIFF;
  TITLE 'MSM FINAL ANALYSIS MODEL';
  ODS OUTPUT LSMEANS=LSMEANS;
RUN;
PROC SQL;
  CREATE TABLE LSMEANS3 AS
    SELECT OPIyn, VISIT_, MEAN(ESTIMATE) AS ESTIMATE
    FROM LSMEANS
    GROUP OPIyn, VISIT_  ;
QUIT;
