proc psmatch data=combined0;
  class rctflag Stent Female Diabetic AcuteMI;
  psmodel rctflag(Treated = '1') = height ejfract Stent Female Diabetic AcuteMI
     ves1proc;
  output out=ps0 ps=pr_rct0;  run;
proc psmatch data=combined1;
  class rctflag Stent Female Diabetic AcuteMI;
  psmodel rctflag(Treated = '1') = height ejfract Stent Female Diabetic AcuteMI
        ves1proc;
  output out=ps1 ps=pr_rct1;  run;
data ps1;
  set ps1;
  if RctFlag = 1 then wt = (1 - pr_rct1) / pr_rct1;
  if RctFlag = 0 then wt = 1;
  dum = 1; run;
data ps0;
  set ps0;
  if RctFlag = 1 then wt = (1 - pr_rct0) / pr_rct0;
  if RctFlag = 0 then wt = 1;
  dum = 1; run;
* Step 2: Rescale Weights such that the sum of weights is the N for the RCT *;
* part a);
  proc means data=ps1;
    where RctFlag = 1;
    var wt;
       output out=mn1 sum=sumwt mean=meanwt n=nwt;
    title 'Summary of weights before re-scaling'; run;
  proc print data=mn1;
    title 'testing output from Means procedure'; run;
  data mn1;
    set mn1;
    dum=1;
    keep dum meanwt;
  proc sort data=mn1; by dum; run;
  proc sort data=ps1; by dum; run;
  data ps1_rct;
    merge ps1 mn1;
       by dum;
       if RCTflag = 1;
    rwt = wt / meanwt;
       inv_rwt = 1 / rwt;
       wy = rwt*cardcost;
       rwtsq = rwt*rwt;
       run;
* part b (control RCT patents);
  proc means data=ps0;
    where RctFlag = 1;
    var wt;
       output out=mn0 sum=sumwt mean=meanwt n=nwt;
    title 'Summary of weights before re-scaling'; run;
  proc print data=mn0;
    title 'testing output from Means procedure'; run;
  data mn0;
    set mn0;
    dum=1;
    keep dum meanwt;
  proc sort data=mn0; by dum; run;
  proc sort data=ps0; by dum; run;
  data ps0_rct;
    merge ps0 mn0;
       by dum;
       if RCTflag = 1;
    rwt = wt / meanwt;
       inv_rwt = 1 / rwt;
       wy = rwt*cardcost;
       rwtsq = rwt*rwt;
       run;
* merge back two parts of RCT sample;
data ps_rct;
  set ps1_rct ps0_rct; run;
proc means data=ps_rct n mean std min p10 median p90 max;
    class thin;
    var rwt;
    title 'Distribution of Rescaled Weights for RCT patients by treatment group'; run;
* Compute the Effective Sample Size *;
proc means data=ps_rct n mean sum std;
  var rwt rwtsq;
  output out=ESS sum = sum_rwt sum_rwtsq;
  title 'ESS calculations'; run;
data ess;
  set ess;
  effss = (sum_rwt**2) / sum_rwtsq;
proc print data=ess;
  title 'testing ESS'; run;
* Step 3: Estimated Re-Weighted Treatment Effect from the RCT *;
proc genmod data=ps_rct;
    weight rwt;
    class trt patid;
    model Cardcost = trt;
    repeated subject=patid; * REPEATED added to get "sandwich"
                              error estimation;
    lsmeans trt / pdiff;
    title 'IPW Weighted Analysis using GENMOD with sandwich error estimation';
run;
proc genmod data=ps_rct;
    weight rwt;
    class trt patid;
    model Cardcost = trt height ejfract stent diabetic acutemi female;
    repeated subject=patid; * REPEATED added to get "sandwich"
                              error estimation;
    lsmeans trt / pdiff;
    title 'IPW Weighted Analysis using GENMOD with sandwich error estimation';
run;
* rename dataset if running later EB code after this code as a single program;
data ps1_rct;
  set ps_rct; run;
