proc print data=t1w (obs=10);
  title 'test listing of t1w'; run;
data EB;
  set t1w t0w;
  w_eb = w;
  keep patid w_eb;
proc sort data=EB; by patid; run;
proc sort data=ps1_rct; by patid; run;
data eb;
  merge eb ps1_rct;
  by patid; run;
proc print data=EB (obs=5);
   title 'test listing of EB weights'; run;
proc means data=eb n mean std min p10 median p90 max;
   class thin;
   var w_eb ;
   title 'Summary of EB weights by Treatment Group'; run;
proc genmod data=eb;
    weight w_eb;
    class thin patid;
    model Cardcost = thin;
    repeated subject=patid; * REPEATED added to get "sandwich" error estimation;
    lsmeans thin / pdiff;
    title 'Entropy Weighted Analysis using GENMOD with sandwich error estimation';
run;
proc genmod data=eb;
    weight w_eb;
    class thin patid;
    model Cardcost = thin height ejfract stent diabetic acutemi female;
    repeated subject=patid; * REPEATED added to get "sandwich" error estimation;
    lsmeans thin / pdiff;
    title 'Entropy Weighted Analysis using GENMOD with sandwich error estimation';
run;
* This repeats the above Entropy Re-weighting analysis except the weights are computed only once for the full RCT sample
(treatment groups combined);
data t0t1;
  set ps1_rct;
  run;
title1 "entropy balancing to generate weights for the RCT population";
