data ps1_rctw;
    set ps1_rctw;
    w_eb = w;
    keep patid w_eb;
proc sort data=ps1_rctw;  by patid; run;
proc sort data=ps1_rct;   by patid; run;
data ps1_rctw;
    merge ps1_rctw ps1_rct;
       w_ebsq = w_eb*w_eb;
    by patid; run;
proc means data=ps1_rctw n mean std min p10 median p90 max;
    class thin;
    var w_eb ;
    title 'Summary of EB weights by Treatment Group'; run;
proc genmod data=ps1_rctw;
    weight w_eb;
    class thin patid;
    model Cardcost = thin;
    repeated subject=patid; * REPEATED added to get "sandwich" error estimation;
    lsmeans thin / pdiff;
    title 'Weighted Analysis using GENMOD with sandwich error estimation';
run;
proc genmod data=ps1_rctw;
    weight w_eb;
    class thin patid;
    model Cardcost = thin height ejfract stent diabetic acutemi female;
    repeated subject=patid; * REPEATED added to get "sandwich" error estimation;
    lsmeans thin / pdiff;
    title 'Weighted Analysis using GENMOD with sandwich error estimation';
run;
proc means data=ps1_rctw n mean sum std;
  var w_eb w_ebsq;
  output out=ESS sum = sum_web sum_websq;
  title 'ESS calculations'; run;
data ess;
  set ess;
  effss = (sum_web**2) / sum_websq;
proc print data=ess;
  title 'testing ESS'; run;
