DATA PEOPLE;
   INFORMAT LASTNAME FIRSTNAME $12. AGE 3. SCORE 4.2;
   INPUT LASTNAME FIRSTNAME AGE SCORE;
   DATALINES;
Lincoln   George    35 3.45
Ryan      Lacy      33 5.5
;
PROC PRINT DATA=PEOPLE;
RUN;
