  DATA TABLE;
  INPUT A B COUNT;
  DATALINES;
  0 0 12
  0 1 15
  1 0 18
  1 1 3
  ;
  ODS TRACE ON;
  PROC FREQ;WEIGHT COUNT;
     TABLES A*B /CHISQ;
     TITLE 'CHI-SQUARE ANALYSIS FOR A 2X2 TABLE';
  RUN;
