  DATA WT;
  INPUT WEIGHT @@;
  DATALINES;
  64 71 53 67 55 58
  77 57 56 51 76 68
  ;
  DATA WTDIFF;SET WT;
  IF :=1 THEN SET STATS;
  DIFF=WEIGHT-WEIGHT_MEAN;
  Z=DIFF/WEIGHT_STDDEV; * Creates standardized scoreE (Z-score);
  RUN;
  PROC PRINT DATA= WTDIFF;VAR WEIGHT DIFF Z;
  RUN;
