 DATA COINS;
         INPUT @1 CATEGORY $9. @11 NUMBER 3.;
 DATALINES;
 CENTS    152
 CENTS    100
 NICKELS  49
 DIMES    59
 QUARTERS 21
 HALF     44
 DOLLARS  21
 ;
 PROC FREQ; WEIGHT NUMBER;
   TITLE 'Reading Summarized Count data';
  TABLES CATEGORY;
 RUN;
