%MACRO
%MEND
macroname
%MACRO
%MEND
REPORT
SUBJECTS
DSN
&SUBJ
&DSN
%MACRO REPORT(SUBJ, DSN);
     DATA REPORT;SET "&DSN";
     IF SUBJ=&SUBJ;
     TITLE "REPORT ON SUBJECT # &SUBJ";
      PROC PRINT NOOBS DATA=REPORT;
          VAR GENDER TIME_EXPOSED DIAGNOSED;
      RUN;
