%MACRO REPORT(SUBJ, DSN);
     DATA REPORT;SET "&DSN";
     IF SUBJ=&SUBJ;
     TITLE "REPORT ON SUBJECT # &SUBJ";
      PROC PRINT NOOBS DATA=REPORT;
          VAR GENDER TIME_EXPOSED DIAGNOSED;
      RUN;
%MEND REPORT;
