%MACRO CARMPG2(4);
DATA CYLINDERS&B;
     SET MYSASLIB.AUTOMPG;
     WHERE CYLINDERS=&B;
  RUN;
  TITLE " Miles Per Gallon Averages for CYLINDERS = &B ";
  PROC MEANS DATA=CYLINDERS&B;
  VAR CITYMPG HWYMPG;
  RUN;
