 PROC TEMPLATE; LIST STYLES; RUN;
STYLES.DEFAULT
PROC TEMPLATE
STYLES
WORD
ODS1A.SAS
ODS1.SAS
 DATA TEST; SET "C:\SASDATA\SOMEDATA";
 * DEFINE WHERE WORD OUTPUT WILL GO;
 TITLE 'ODS WORD Example';
 ODS WORD FILE='c:\SASDATA\ODS.docx';
 PROC MEANS MAXDEC=2; VAR AGE TIME1-TIME4;
 RUN;
