 ODS _ALL_ CLOSE;
 TITLE1 "PowerPoint Slide Example";
 FOOTNOTE "US Map By Population";
 ODS POWERPOINT FILE="C:\SASDATA\POP.PPTX";
 PROC GMAP DATA = MYSASLIB.POP2019 MAP=MAPS.US;
     ID STATE;
     CHORO POP_2019;
 RUN;
 QUIT;
 ODS _ALL_ CLOSE;
PROC GMAP
POP2019
MAPS.US
ID
STATE
STATE
CHORO
CHORO
GMAPS
POP.PPTX
C:\SASDATA
 PROC MEANS DATA=MYSASLIB.POP2019;
 RUN;
