PROC SGPLOT DATA =MYSASLIB.CORONARY;
      TITLE 'BUBBLE PLOT USING CORONARY DATA';
      TITLE2 'Bubble is BMI';
      BUBBLE X = AGE Y = SBP SIZE = BMI
             / TRANSPARENCY = 0.5;
      YAXIS GRID;
RUN;
