proc sort data=SASdata.ADEMEX Adequacy Data out=example2 2 3;
by Trt ptid Month Visit;
run;
ods select Type3 LSMeans;
ods output LSMeans=lsAvgout LSMeanDiffs=lsAvgdiff;
proc genmod data=example2 2 3;
where Month>-1;
class Trt Month ptid;
model pCCR = Trt Month / type3;
repeated subject=ptid / type=cs;
lsmeans Trt /diff cl;
run;
ods select Type3;
ods output LSMeans=lsout LSMeanDiffs=lsdiff;
proc genmod data=example2 2 3; where Month<=28;
class Trt Month ptid;
model pCCR = Trt Month Trt*Month / type3;
repeated subject=ptid / type=cs;
lsmeans Trt*Month /diff cl;
run;
