ods output solutionF=pe1;
ods output covparms=var1;
ods output R=rvar1;
ods output infocrit=IC1;
ods output Dimensions=no subjects1;
proc mixed data=Example2 2 4 ic;
class Subject Core ;
model MCM2Index = Core /solution;
repeated Core / subject=Subject r=2 rcorr=2 type=cs;
run;
ods output solutionF=pe2;
ods output covparms=var2;
ods output R=rvar2;
ods output infocrit=IC2;
ods output Dimensions=no subjects2;
proc mixed data=Example2 2 4 ic;
class Subject Core ;
model MCM2Index = Core /solution;
repeated /subject=Subject r=2 rcorr=2 type=sp(lin) (row col);
run;
data IC1;
set IC1;
Model=1;
Covariance='Compound Symmetry';
run;
data IC2;
set IC2;
Model=2;
Covariance='Spatial Linearity';
run;
