PROC SGPLOT DATA=SASMTS.EGG;
    SERIES Y=QEGG X=DATE/MARKERS MARKERATTRS=(SYMBOL=CIRCLE
COLOR=BLUE);
    SERIES Y=PEGG X=DATE/MARKERS MARKERATTRS=(SYMBOL=TRIANGLE
COLOR=RED);
    SERIES Y=QTOT X=DATE/MARKERS MARKERATTRS=(SYMBOL=SQUARE
COLOR=GREEN);
    SERIES Y=PTOT X=DATE/MARKERS MARKERATTRS=(SYMBOL=HASH
COLOR=BROWN);
RUN;
