PROC VARMAX DATA=SASMTS.EGG;
    MODEL QEGG PEGG = QTOT PTOT/DIF=(QEGG(1) PEGG(1) QTOT(1)
PTOT(1))
        NSEASON=12 P=2 XLAG=2 METHOD=ML;
    CAUSAL GROUP1=(QEGG) GROUP2=(PEGG);
RUN;
PROC VARMAX DATA=SASMTS.EGG;
    MODEL QEGG PEGG = QTOT PTOT/DIF=(QEGG(1) PEGG(1) QTOT(1)
PTOT(1))
        NSEASON=12 P=2 XLAG=2 METHOD=ML;
    CAUSAL GROUP1=(PEGG) GROUP2=(QEGG);
RUN;
