%let wf=3;
data mycas.weighted_factmac / single=no;
    set mycas.implict_feedback;
    if _n_=1 then do;
        declare hash conv (dataset:'mycas.conversation_uid_index');
        conv.DefineKey('conversation_ord');
        conv.DefineData('start_id', 'end_id');
        conv.DefineDone();
        declare hash row_lookup (dataset: "mycas.conversations");
        row_lookup.DefineKey('id');
        row_lookup.DefineData('event_time_ms', 'isSolvedTopic');
        row_lookup.DefineDone();
    end;
    if rating=0 then do;
        conv.find();
        id = (start_id + floor((1+end_id-start_id)*rand("uniform")));
        row_lookup.find();
    end;
    decay = (datepart(event_time_ms)-&mindate.)/(&maxdate. - &mindate.);
    rep = int((1-decay)*10);
    daysback = intck("DAYS", datepart(event_time_ms), today(), "C");
    do i = 1 to rep*&wf.;
        output;
    end;
run;
